POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "full_name": "admin",
  "password": "admin123",
  "email": "admin@cowrk.com",
  "role": "admin"

}
###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "full_name": "user",
  "password": "user123",
  "email": "user@cowork.com"
  
}
###
GET  http://localhost:8080/api